if (Platform.isLoaded('ponderjs')) {
    onEvent('ponder.registry', event => {
        event.create('minecraft:netherrack')
            .scene('nether_spread', '下界侵染', 'kubejs:nether_portal_basic', (scene, util) => {
                scene.scaleSceneView(0.8)
                scene.configureBasePlate(0, 0, 6)
                scene.showBasePlate()
                scene.idle(10)
                scene.world.showSection([2, 1, 1], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 1, 2], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 1, 3], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 1, 4], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 2, 1], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 2, 4], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 3, 1], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 3, 4], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 4, 1], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 4, 4], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 5, 1], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 5, 2], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 5, 3], Facing.DOWN)
                scene.idle(2)
                scene.world.showSection([2, 5, 4], Facing.DOWN)
                scene.idle(10)
                scene.showControls(20, [2.5, 2, 2.5], 'down')
                    .rightClick()
                    .withItem('flint_and_steel')
                scene.idle(20)
                scene.addKeyframe()
                scene.world.showSection([2, 2, 2, 2, 4, 3], Direction.DOWN)
                scene.idle(10)
                for (let i = 0; i < 5; i++) {
                    for (let j = 0; j < 6; j++) {
                        if (i == 2 && j >= 1 && j <= 4) continue
                        scene.world.showSection([i, 1, j], Facing.DOWN)
                        scene.idle(2)
                    }
                }
                scene.text(20, '这些方块可以被下界传送门侵染成下界的方块。', [1.5, 2, 1.5])
                scene.idle(25)
                scene.addKeyframe()
                scene.overlay.showSelectionWithText([2, 2, 2], 40)
                    .text('点火位置')
                    .pointAt([2.2, 2.5, 2.5])
                    .colored('red')
                scene.world.setBlock([1, 1, 2], 'netherrack', false)
                scene.world.setBlock([3, 1, 2], 'soul_sand', false)
                scene.text(40, '下界传送门从进到远侵染方块，距离从点火位置开始计算。该方块的距离为二，最先被转换。', [2.2, 1, 3.5])
                scene.idle(50)
                scene.rotateCameraY(90)
                scene.addKeyframe()
                scene.idle(20)
                scene.text(40, '方块的侵染结果会有所不同，如这里被侵染成灵魂沙', [4.5, 3, 1.5])
                scene.idle(40)
                scene.addKeyframe()
                scene.world.setBlock([3, 1, 3], 'soul_sand', false)
                scene.world.setBlock([3, 1, 1], 'soul_sand', false)
                scene.world.setBlock([4, 1, 2], 'soul_soil', false)
                scene.idle(10)
                scene.text(80, '下界的蔓延会随机根据某一生物群系选择方块。若某一方块与某一下界生物群系的方块相邻，则它只能侵染成该生物群系的方块。该方块与灵魂沙峡谷的灵魂沙相连，故只能侵染成灵魂沙或灵魂土。', [3.2, 1, 3.2])
                scene.idle(90)
                scene.addKeyframe()
                scene.overlay.showSelectionWithText([2, 2, 2], 80)
                    .text('点火位置')
                    .pointAt([2.5, 2.2, 2.6])
                    .colored('red')
                scene.overlay.showOutline('blue', [3, 1, 3], [3, 1, 3], 90)
                scene.overlay.showOutline('blue', [3, 1, 1], [3, 1, 1], 90)
                scene.overlay.showSelectionWithText([4, 1, 2], 80)
                    .colored('blue')
                    .pointAt([3.2, 1, 3.2])
                    .text('下界传送门会同时侵染 x 个距离为 x 的方块。如这三个方块与点火位置距离为三，被同时侵染。')
                scene.idle(90)
                scene.rotateCameraY(-90)
                scene.addKeyframe()
                scene.idle(20)
                scene.world.setBlock([1, 1, 1], 'netherrack', false)
                scene.world.setBlock([1, 1, 3], 'nether_gold_ore', false)
                scene.world.setBlock([0, 1, 2], 'nether_quartz_ore', false)
                scene.idle(10)
                scene.overlay.showSelectionWithText([2, 2, 2], 540)
                    .text('点火位置')
                    .pointAt([2.2, 2.5, 2.5])
                    .colored('red')
                scene.overlay.showOutline('blue', [1, 1, 1], [1, 1, 1], 90)
                scene.overlay.showOutline('blue', [1, 1, 3], [1, 1, 3], 90)
                scene.overlay.showSelectionWithText([0, 1, 2], 80)
                    .colored('blue')
                    .pointAt([0.5, 2, 2.7])
                    .text('同理，这三个方块被同时侵染成下界荒原的方块：下界岩、下界石英矿石、下界金矿石')
                scene.idle(90)
                scene.addKeyframe()
                scene.idle(30)
                scene.world.setBlock([2, 1, 0], 'basalt', false)
                scene.overlay.showSelectionWithText([2, 1, 0], 80)
                    .colored('blue')
                    .pointAt([2.5, 2, 0.7])
                    .text('该方块与点火位置距离为三，且不与任何一个下界方块相邻，侵染成随机群系的方块，如玄武岩。')
                scene.idle(90)
                scene.addKeyframe()
                scene.world.setBlock([0, 1, 1], 'netherrack', false)
                scene.world.setBlock([1, 1, 4], 'netherrack', false)
                scene.world.setBlock([4, 1, 1], 'soul_soil', false)
                scene.world.setBlock([3, 1, 0], 'soul_sand', false)
                scene.overlay.showSelectionWithText([0, 1, 1], 40)
                    .colored('blue')
                    .pointAt([0.5, 2, 1.7])
                    .text('只有距离二和三没有可侵染的方块后才会侵染距离四的方块。随机侵染四个。')
                scene.overlay.showOutline('blue', [1, 1, 4], [1, 1, 4], 50)
                scene.overlay.showOutline('blue', [4, 1, 1], [4, 1, 1], 50)
                scene.overlay.showOutline('blue', [3, 1, 0], [3, 1, 0], 50)
                scene.idle(60)
                scene.world.setBlock([1, 1, 0], 'blackstone', false)
                scene.world.setBlock([0, 1, 3], 'nether_gold_ore', false)
                scene.world.setBlock([4, 1, 3], 'soul_soil', false)
                scene.world.setBlock([3, 1, 4], 'soul_sand', false)
                scene.overlay.showSelectionWithText([0, 1, 3], 40)
                    .colored('blue')
                    .pointAt([0, 1.5, 3.5])
                    .text('再随机侵染四个距离为四的方块。')
                scene.overlay.showOutline('blue', [1, 1, 0], [1, 1, 0], 50)
                scene.overlay.showOutline('blue', [4, 1, 3], [4, 1, 3], 50)
                scene.overlay.showOutline('blue', [3, 1, 4], [3, 1, 4], 50)
                scene.idle(50)
                scene.addKeyframe()
                scene.overlay.showSelectionWithText([1, 1, 0], 80)
                    .colored('blue')
                    .pointAt([1.5, 2, 0.7])
                    .text('若一个方块同时与不同下界群系的方块相邻，则会随机侵染成其中一个群系的方块。')
                scene.idle(90)
                scene.addKeyframe()
                scene.idle(20)
                scene.world.setBlock([2, 1, 5], 'netherrack', false)
                scene.idle(40)
                scene.world.setBlock([0, 1, 0], 'blackstone', false)
                scene.world.setBlock([4, 1, 0], 'soul_sand', false)
                scene.world.setBlock([0, 1, 4], 'netherrack', false)
                scene.world.setBlock([3, 1, 5], 'soul_sand', false)
                scene.world.setBlock([4, 1, 4], 'soul_soil', false)
                scene.idle(40)
                scene.world.setBlock([1, 1, 5], 'nether_quartz_ore', false)
                scene.idle(40)
                scene.world.setBlock([0, 1, 5], 'netherrack', false)
                scene.world.setBlock([4, 1, 5], 'soul_sand', false)
                scene.idle(10)
                scene.rotateCameraY(90)
            })
            .scene('nether_spread_modifier', '下界传送门的变化', 'kubejs:nether_portal_basic', (scene, util) => {
                scene.scaleSceneView(0.8)
                scene.configureBasePlate(0, 0, 6)
                scene.showStructure()
                scene.idle(100)
                scene.world.setBlock([1, 1, 2], 'netherrack', false)
                scene.world.setBlock([3, 1, 2], 'soul_sand', false)
                scene.text(40, '默认情况下，每隔 5 秒传送门尝试侵染方块一次。', [2.2, 1, 3.5])
                scene.idle(40)
                scene.addKeyframe()
                tossItem(scene, 'thermal_extra:soul_infused_dust')
                scene.idle(40)
                scene.world.setBlock([1, 1, 1], 'netherrack', false)
                scene.world.setBlock([1, 1, 3], 'nether_gold_ore', false)
                scene.world.setBlock([0, 1, 2], 'nether_quartz_ore', false)
                scene.text(80, '投入注灵粉后，在接下来的 400 秒内，下界传送门将会加快到每隔 2 秒侵染方块。')
                    .pointAt([0.5, 2, 2.7])
                scene.idle(40)
                scene.world.setBlock([3, 1, 3], 'soul_sand', false)
                scene.world.setBlock([3, 1, 1], 'soul_sand', false)
                scene.world.setBlock([4, 1, 2], 'soul_soil', false)
                scene.idle(40)
                scene.world.setBlock([2, 1, 0], 'basalt', false)
                scene.addKeyframe()
                scene.idle(5)
                tossItem(scene, 'thermal_extra:twinite_dust')
                scene.idle(40)
                scene.world.setBlock([0, 1, 1], 'netherrack', false)
                scene.world.setBlock([1, 1, 4], 'netherrack', false)
                scene.world.setBlock([4, 1, 1], 'soul_soil', false)
                scene.world.setBlock([3, 1, 0], 'soul_sand', false)
                scene.idle(40)
                scene.world.setBlock([1, 1, 0], 'ancient_debris', false)
                scene.world.setBlock([0, 1, 3], 'nether_gold_ore', false)
                scene.world.setBlock([4, 1, 3], 'soul_soil', false)
                scene.world.setBlock([3, 1, 4], 'soul_sand', false)
                scene.text(120, '投入双子物质粉后，每个方块被侵染时都有 1%% 的机会变成远古残骸。当方块变成远古残骸后，有 25%% 几率双子物质粉的效果结束。注灵粉和双子物质粉的效果可以叠加。', [1.5, 2, 0.7])
                scene.idle(120)
                scene.addKeyframe()
                tossItem(scene, 'coal')
                scene.idle(20)
                scene.text(40, '投入煤炭后，传送门将不再侵染方块，除非破坏传送门重新点燃。', [2.2, 2.5, 2.5])
                scene.idle(40)
            })
            .scene('nether_spread_redstone', '下界传送门的红石监测', 'kubejs:nether_portal_basic', (scene, util) => {
                scene.scaleSceneView(0.8)
                scene.configureBasePlate(0, 0, 6)
                scene.showBasePlate()
                scene.world.showIndependentSectionImmediately([2, 1, 1, 2, 5, 4])
                scene.world.showIndependentSectionImmediately([0, 1, 0, 4, 1, 5])
                scene.idle(10)
                scene.world.setBlock([0, 2, 4], 'composter', false)
                scene.world.showSection([0, 2, 4], 'down')
                scene.idle(5)
                scene.world.setBlock([0, 2, 3], 'comparator', false)
                scene.world.modifyBlock([0, 2, 3], it => it.with('facing', 'south'), false)
                scene.world.showSection([0, 2, 3], 'down')
                scene.idle(5)
                scene.world.setBlock([0, 2, 2], 'redstone_wire', false)
                scene.world.modifyBlock([0, 2, 2], it => it.with('north', 'side').with('south', 'side'), false)
                scene.world.showSection([0, 2, 2], 'down')
                scene.idle(5)
                scene.text(60, '在下界传送门的侵染范围内放置一个堆肥桶可以监测其的状态。', [0, 2.5, 4.7])
                scene.idle(60)
                scene.addKeyframe()
                tossItem(scene, 'thermal_extra:soul_infused_dust')
                scene.idle(20)
                scene.world.setBlock([1, 1, 2], 'netherrack', false)
                scene.world.setBlock([3, 1, 2], 'soul_sand', false)
                scene.world.modifyBlock([0, 2, 4], it => it.with('level', 3), false)
                scene.world.modifyBlock([0, 2, 3], it => it.with('powered', true), false)
                scene.world.modifyBlock([0, 2, 2], it => it.with('power', 3), false)
                scene.text(60, '当注灵粉的效果结束后，比较器发出强度为 3 的红石脉冲。', [0, 2.1, 3.7])
                scene.idle(60)
                scene.addKeyframe()
                scene.world.modifyBlock([0, 2, 4], it => it.with('level', 0), false)
                scene.world.modifyBlock([0, 2, 3], it => it.with('powered', false), false)
                scene.world.modifyBlock([0, 2, 2], it => it.with('power', 0), false)
                tossItem(scene, 'thermal_extra:twinite_dust')
                scene.idle(20)
                scene.world.setBlock([1, 1, 1], 'ancient_debris', false)
                scene.world.setBlock([1, 1, 3], 'nether_gold_ore', false)
                scene.world.setBlock([0, 1, 2], 'nether_quartz_ore', false)
                scene.text(60, '有方块转换成远古残骸时，若双子物质粉的效果未失效，比较器不会发出信号。', [0, 2.1, 3.7])
                scene.idle(80)
                scene.world.setBlock([3, 1, 3], 'soul_sand', false)
                scene.world.setBlock([3, 3, 1], 'soul_sand', false)
                scene.world.setBlock([2, 1, 0], 'ancient_debris', false)
                scene.world.modifyBlock([0, 2, 4], it => it.with('level', 6), false)
                scene.world.modifyBlock([0, 2, 3], it => it.with('powered', true), false)
                scene.world.modifyBlock([0, 2, 2], it => it.with('power', 6), false)
                scene.text(60, '当双子物质粉的效果结束后，比较器发出强度为 6 的红石脉冲。', [0, 2.1, 3.7])
                scene.idle(60)
                scene.world.modifyBlock([0, 2, 4], it => it.with('level', 0), false)
                scene.world.modifyBlock([0, 2, 3], it => it.with('powered', false), false)
                scene.world.modifyBlock([0, 2, 2], it => it.with('power', 0), false)
                scene.addKeyframe()
                scene.world.setBlock([4, 2, 0], 'composter', false)
                scene.world.showSection([4, 2, 0], 'down')
                scene.idle(5)
                scene.world.setBlock([3, 2, 0], 'comparator', false)
                scene.world.modifyBlock([3, 2, 0], it => it.with('facing', 'east'), false)
                scene.world.showSection([3, 2, 0], 'down')
                scene.idle(10)
                tossItem(scene, 'thermal_extra:twinite_dust')
                scene.idle(20)
                scene.world.setBlock([3, 1, 1], 'ancient_debris', false)
                scene.world.modifyBlock([4, 2, 0], it => it.with('level', 6), false)
                scene.world.modifyBlock([3, 2, 0], it => it.with('powered', true), false)
                scene.overlay.showSelectionWithText([3, 2, 0], 60)
                    .text('一个传送门只能被一个堆肥桶监测。当放置多个堆肥桶时，只有最后放置的生效。')
                    .pointAt([3, 2.1, 0.7])
                    .colored('green')
                scene.overlay.showSelectionWithText([0, 2, 3], 60)
                    .text('不产生信号。')
                    .pointAt([0, 2.5, 3.7])
                    .colored('red')
                scene.idle(60)
            })
    })
}

function tossItem(scene, item) {
    let entity = scene.world.createItemEntity([1.5, 3, 2.5], [0, 0, 0], item)
    scene.world.modifyEntity(entity, it => it.setNoGravity(true))
    scene.showControls(30, [1.3, 3.5, 2.5], 'left').withItem(item)
    scene.idle(40)
    scene.world.modifyEntity(entity, it => {
        it.setNoGravity(false)
        it.setDeltaMovement(0.1, 0.1, 0)
    })
    scene.idle(5)
    scene.world.modifyEntity(entity, it => {
        it.asKJS().remove()
    })
}